import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import NavBar from "./nav-bar";
import { Theme } from "@radix-ui/themes";

const inter = Inter({ subsets: [ "latin" ] });

export const metadata: Metadata = {
  title: "Issue Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <NavBar/>
          <main>
            {children}
          </main>
        </Theme>
      </body>
    </html>
  );
}
