import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import NavBar from "./nav-bar";
import { Theme } from "@radix-ui/themes";

const inter = Inter({
  subsets: [ "latin" ],
  display: "swap",
  variable: "--font-inter"
});

export const metadata: Metadata = {
  title: "Issue Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <Theme
          appearance="light"
          accentColor="cyan"
          grayColor="auto"
          scaling="100%"
        >
          <NavBar/>
          <main className="p-5">
            {children}
          </main>
        </Theme>
      </body>
    </html>
  );
}

